---
AWSTemplateFormatVersion: 2010-09-09

Description: |
  CloudFormation template to deploy the Kittens Carousel web application |

#Parameters:

Resources: 

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enagble HTTP and SSH for webserver
      GroupName: WebServerSecGroup
      SecurityGroupIngress: 
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

#Outputs: