  AWSTemplateFormatVersion: 2010-09-09
  Description: |
    CloudFormation Template to deploy the Roman Numerial Converter web application

  #Parameters:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH for webserver # Required
      GroupName: WebserverSecGrp 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  MyEC2Instance: #An inline comment
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "String"
      InstanceType: "String"
      KeyName: "String"
      SecurityGroupIds:
        -!Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: RomanNumerialWebServer-Oguz
      UserData: "String"
    

  Metadata:
    
  Mappings:
    
  Conditions:
    
  Resources:
    
  Transform:
    
  Outputs: